apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
    heritage: 1pro
  name: app
spec:
  selector:
    matchLabels:
      type: app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: app
          image: 1pro/app:v1
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
            limits:
              memory: "200Mi"
              cpu: "50m"