apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    part: 1
    section: 2
    class: 2
    step: 1
    app: app-1-2-2-1
    heritage: 1pro
  name: app-1-2-2-1
spec:
  selector:
    matchLabels:
      part: 1
      section: 2
      class: 2
      step: 1
      app: app-1-2-2-1
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part: 1
        section: 2
        class: 2
        step: 1
        app: app-1-2-2-1
    spec:
      containers:
        - name: app-1-2-2-1
          image: 1pro/app
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "100m"