apiVersion: v1
kind: Service
metadata:
  name: app-1-2-2-1
spec:
  selector:
    part: 1
    section: 2
    class: 2
    step: 1
    app: app-1-2-2-1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31221
  type: NodePort